tags_list = [
    {
        "name": "Educação",
        "keywords": [
            "ifes",
            "ufes",
            "escola",
            "educação",
            "ensino",
            "aluno",
            "alunos",
            "universidade",
            "capacitação",
            "treinamento",
            "curso",
            "formação",
            "aprendizagem",
            "estudante",
            "pesquisa",
            "pesquisador",
        ],
    },
    {
        "name": "Meio Ambiente",
        "keywords": [
            "meio ambiente",
            "ambiental",
            "sustentabilidade",
            "sustentável",
            "licenciamento ambiental",
            "ibama",
            "iema",
            "fauna",
            "flora",
            "manguezal",
            "ecossistema",
            "preservação",
            "conservação",
            "compensação ambiental",
            "monitoramento ambiental",
            "carbono",
            "emissões",
            "biodiversidade",
        ],
    },
    {
        "name": "Impacto Social",
        "keywords": [
            "comunidade",
            "impacto social",
            "cidadania",
            "inclusão",
            "qualidade de vida",
            "moradores",
            "famílias",
            "mulheres",
            "feminino",
            "juventude",
            "social",
            "desenvolvimento humano",
            "projeto social",
            "responsabilidade social",
        ],
    },
    {
        "name": "Economia",
        "keywords": [
            "economia",
            "emprego",
            "empregos",
            "renda",
            "desenvolvimento",
            "desenvolvimento econômico",
            "socioeconômico",
            "investimento",
            "investimentos",
            "mercado",
            "negócios",
            "crescimento",
            "arrecadação",
            "tributos",
            "receita",
        ],
    },
    {
        "name": "Infraestrutura",
        "keywords": [
            "obra",
            "obras",
            "construção",
            "infraestrutura",
            "terminal",
            "porto",
            "cais",
            "dragagem",
            "acesso viário",
            "rodovia",
            "ferrovia",
            "berço de atracação",
            "expansão",
            "implantação",
        ],
    },
    {
        "name": "Logística",
        "keywords": [
            "logística",
            "transporte",
            "carga",
            "cargas",
            "exportação",
            "importação",
            "armazenagem",
            "escoamento",
            "cadeia logística",
            "terminal logístico",
            "granéis",
            "contêineres",
            "navio",
            "navegação",
        ],
    },
    {
        "name": "Energia",
        "keywords": [
            "energia",
            "petróleo",
            "gás natural",
            "gnl",
            "combustível",
            "offshore",
            "eólica",
            "energia renovável",
            "hidrogênio verde",
            "transição energética",
            "terminal de petróleo",
            "terminal de combustíveis",
        ],
    },
    {
        "name": "Parcerias",
        "keywords": [
            "parceria",
            "acordo",
            "cooperação",
            "memorando",
            "convênio",
            "investidor",
            "empresa",
            "empresas",
            "joint venture",
            "assinatura",
        ],
    },
    {
        "name": "Impacto Internacional",
        "keywords": [
            "internacional",
            "global",
            "mercado internacional",
            "exportação",
            "china",
            "estados unidos",
            "europa",
            "rússia",
            "oriente médio",
            "américa latina",
            "comércio exterior",
        ],
    },
]
